######################################################################
# Automatically generated by qmake (3.1) Sat Oct 22 12:59:44 2022
######################################################################

TEMPLATE = app
TARGET = client
INCLUDEPATH += .

QT += widgets network core

# Input
HEADERS += includes/mainwindow.hpp includes/package.hpp
SOURCES += sources/main.cpp sources/mainwindow.cpp sources/package.cpp
